name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - run: npm i -g --force corepack && corepack enable && corepack enable npm

      - name: Install dependencies
        run: pnpm i

      - name: Build package
        run: pnpm run build

      - name: Run tests
        run: pnpm run test

      - name: Run E2E tests
        working-directory: tests/nextjs
        run: |
          pnpm i
          pnpm exec playwright install
          pnpm run test

      - name: Check formatting
        run: pnpm run format:check

      - name: Check exports
        run: |
          corepack disable npm
          pnpm run exports:check
          corepack enable npm
