name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - run: corepack enable && corepack enable npm

      - name: Install dependencies
        run: pnpm i

      - name: Run tests
        run: pnpm run test

      - name: Check formatting
        run: pnpm run format:check

      - name: Check exports
        run: pnpm run exports:check
